### ISSUE TITLE
Food Order for April 12 OKC JUG Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#10]
Sorry for the late start on this.

Pizza:
-     2 cheese
-     2 pepperoni
-     1 sausage
-     2 supreme
-     2 veggie

Drinks:
-     1 Coke
-     1 Sprite
-     1 Dr. Pepper
-     20 plates

CC: @amandaharlin @drodmaster @rhoegg

**Comment by jasondlee** [comment]
Anyone have the status of this? Please? :)

**Comment by the-simian** [comment]
The food was ordered this morning, should be delivered on time

**Comment by jasondlee** [comment]
Excellent! Thanks. Again, sorry for the late action on my part. Time just keeps slipping away from me. :)

**Comment by the-simian** [comment]
No problem, we actually saw this one coming and started on it early this morning. For some reason the pizza place was having issues with their POS system and it took a while to get it worked out, but its all good.
