### ISSUE TITLE
Food Order for May 10 OKC JUG Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#11]
Getting this one in early. ;)

Meeting Date: May 10

Pizza:
-     2 cheese
-     2 pepperoni
-     1 sausage
-     2 supreme
-     2 veggie

Drinks:
-     1 Coke
-     1 Sprite
-     1 Dr. Pepper
-     20 plates

CC: @amandaharlin @drodmaster @rhoegg

**Comment by jasondlee** [comment]
Too early to file this one? And do "we" prefer the CC or actually assigning the issue?

**Comment by seejessicacode** [comment]
Looks like this issue is no longer relevant. Could you close this @jasondlee?

**Comment by jasondlee** [comment]
Certainly. Sorry. :)
