### ISSUE TITLE
Food Order for September 13 Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#14]
Meeting Date: September 13

Pizza:
-     2 cheese
-     2 pepperoni
-     2 sausage
-     2 supreme
-     2 veggie

Drinks:
-     2 Coke
-     1 Sprite
-     1 Dr. Pepper
-     1 Diet Coke (just for @drodmaster : )
-     20 plates

CC: @amandaharlin @drodmaster @rhoegg

**Comment by seejessicacode** [comment]
@jasondlee please post all food orders to https://github.com/techlahoma/techlahoma/issues

**Comment by jasondlee** [comment]
Sorry. This is how I was told to do it. I'll refile there.
