### ISSUE TITLE
Order pizza for November meeting

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/okcjug-planning#2]
Plan on 18 people, please.   Meeting is on November 10 at 11:30am at Prototek.

**Comment by amandaharlin** [comment]
Thank you! I'll post the receipt next. 😃

**Comment by amandaharlin** [comment]
Order is in place. If you'd like me to modify, please let me know!

![screenshot_2015-11-09-22-23-03](https://cloud.githubusercontent.com/assets/716644/11054382/06533c84-8731-11e5-8342-615b81f49f33.jpg)
