### ISSUE TITLE
Order Pizza for January Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#4]
The same order as December should work fine?

Meeting is tomorrow 11:30am today

CC: @amandaharlin @drodmaster @rhoegg

**Comment by jasondlee** [comment]
We'll need sodas as well. Types and quantities? @drodmaster?

**Comment by rhoegg** [comment]
I'd suggest 2 pepperoni, 1 sausage, 1 cheese, 1 veggie (5 total).  For beverages, we'd like coke, diet coke, sprite, water. 2 liters or cans are fine, @amandaharlin had a good observation that cans keep better.

**Comment by drodmaster** [comment]
I agree with Ryan on the soda types. 2 coke, 1 diet code and 1 sprite. The
cans are nice but I can't keep storing them month to month. They take up a
lot of room and are very heavy. Unless we have a secure place to store them
at ProtoTek I would rather just have 2 liter bottles that can be sent home
with people at the end of the meeting.

**Comment by jasondlee** [comment]
With whom is the order placed (name, address, and phone) and who places it? I'm assuming me.

**Comment by the-simian** [comment]
I wouldn't count on using Prototek to store cans of soda, (unless you don't mind the members there having a drink now and then). If the cans are too troublesome, then just do two liter containers. 

@rhoegg I have tons of red cups available, if you need some.

**Comment by the-simian** [comment]
offtopic - but  I'm trying to spread the word to every meetup:

When you meet at Prototek, make sure to take some time and clean up the meeting area afterwards. I've caught word that some groups are leaving a mess. Noone knows which one it is, so I'm telling everyone : Be Clean. Prototek is very nice to let us use their facilities.

**Comment by jasondlee** [comment]
Noted. I hope that wasn't us. We try to clean up, so I don't think it would be, but we'll make sure.

**Comment by drodmaster** [comment]
We could sure use some cups. I'll try to get some more for our supplies.

**Comment by amandaharlin** [comment]
pizza places don't offer large bottles of water. their cost for an 8-16 oz bottle is just too high to order for 20+ people.

**Comment by amandaharlin** [comment]
pizza & drinks are ordered! :+1: on thursday we can bring up some of our red cups and leave some at prototek.
<img width="560" alt="screen shot 2016-01-12 at 1 33 37 am" src="https://cloud.githubusercontent.com/assets/716644/12257453/880ac8e2-b8cc-11e5-8dcc-4d6582270855.png">

ryan, if you need anything please let us know. we're here for #teamhoegg.

**Comment by drodmaster** [comment]
I still have 2 large jugs of water that I will be bringing today, so water
is not an issue. Thanks Amanda for getting the pizza and sodas taken care
of. I will get some cups to replenish our supply.
