### ISSUE TITLE
Order Pizza for February Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#5]
I think we can just clone last month's order:

- 1 Cheese
- 2 Pepperoni
- 1 Italian sausage
- Supreme
- 2 Cokes
- 1 Diet Coke
- 1 Sprite

An extra pepperoni and a Coke (or Dr. Pepper) wouldn't hurt. Thoughts?

CC: @amandaharlin @drodmaster @rhoegg

**Comment by drodmaster** [comment]
Jason,

I have an unopened bottle of Coke from last month's meeting. I would change
that to 1 Coke, 2 Diet Cokes and 1 Sprite.

Brent

**Comment by jasondlee** [comment]
Didn't we run out of drinks last time? Or pizza? My memory's fuzzy, but I thought we ran out of something. :P

**Comment by drodmaster** [comment]
We did go through all of the pizza, so an extra pizza would be great.

**Comment by darkfrog26** [comment]
I would like to vote for adding Dr. Pepper.
---
Matt Hicks

Chief Technology OfficerT: 405.283.6887  |  outr.com





On Tue, Feb 9, 2016 at 8:25 AM Brent Wilkins <notifications@github.com> wrote:
We did go through all of the pizza, so an extra pizza would be great.

On Tue, Feb 9, 2016 at 8:16 AM, Jason Lee < notifications@github.com > wrote:

> Didn't we run out of drinks last time? Or pizza? My memory's fuzzy, but I
> thought we ran out of something. :P
>
> —
> Reply to this email directly or view it on GitHub
> < https://github.com/ techlahoma/okcjug-planning/ issues/5#issuecomment-
181881816 >

**Comment by rhoegg** [comment]
I just got a coupon code for Marco's just now: 441607806938

**Comment by rhoegg** [comment]
Ordering it now

**Comment by rhoegg** [comment]
Ordered from Joeys:

- 1 cheese
- 2 pepperoni
- 1 sausage
- 1 supreme
- 1 veggie

- 2 Diet Coke
- 1 Coke
- 1 Sprite
- 1 Dr. Pepper
- 20 plates

Delivery courtesy of me. :)
