### ISSUE TITLE
Title and topic for March Meeting 

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/okcjug-planning#6]
Intro to CD

**Comment by jasondlee** [comment]
- [ ] Get title and abstract from @rhoegg 
- [ ] Update okcjug.org
- [ ] Post to Google+

**Comment by rhoegg** [comment]
## Intro to Continous Delivery
Continuous delivery is a central theme in the DevOps movement, and certainly a central component of the culture. It is the set of engineering techniques, practices, processes, and tools for releasing changes to software services frequently and reliably.

We’ll review the concepts involved in CD, take a look a working CD pipeline for an example application, and discuss how this could apply to other projects.

**Comment by drodmaster** [comment]
Ryan,

Is this for the March, April or May talk. Are you the speaker on this topic?

**Comment by rhoegg** [comment]
This is March, and yes I am the speaker
