### ISSUE TITLE
Order Pizza for March 8 Meeting

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/okcjug-planning#9]
Getting this going well ahead of time this go 'round. :)

Pizza:
- 2 cheese
- 2 pepperoni
- 1 sausage
- 2 supreme
- 2 veggie

Drinks:
- 1 Coke
- 1 Sprite
- 1 Dr. Pepper
- 20 plates

Grazie!

CC: @amandaharlin @drodmaster @rhoegg

**Comment by rhoegg** [comment]
@amandaharlin Are we all set for tomorrow's order?
